{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syncerd.fullname" . }}
  labels:
    {{- include "syncerd.labels" . | nindent 4 }}
{{- end }}
