apiVersion: v2
name: syncerd
description: Your lightweight Docker registry sync engine - sync images from Docker Hub to ECR, ACR, GCR, GHCR
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - docker
  - registry
  - sync
  - ecr
  - acr
  - gcr
  - ghcr
home: https://github.com/clouddrove/syncerd
icon: https://raw.githubusercontent.com/clouddrove/syncerd/master/assets/syncerd-logo.png
sources:
  - https://github.com/clouddrove/syncerd
maintainers:
  - name: CloudDrove
    url: https://clouddrove.com
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/clouddrove/syncerd
    - name: Support
      url: https://github.com/clouddrove/syncerd/issues
  artifacthub.io/maintainers: |
    - name: CloudDrove
      email: hello@clouddrove.com
  artifacthub.io/images: |
    - name: syncerd
      image: ghcr.io/clouddrove/syncerd:latest
